# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'HelloRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloRxSwift

  pod 'RxSwift', '6.0.0-rc.1'
  pod 'RxCocoa', '6.0.0-rc.1'

end
