# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Awesome To Do' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Awesome To Do
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'Awesome To DoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Awesome To DoUITests' do
    # Pods for testing
  end

end
