# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoFilter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoFilter
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'PhotoFilterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoFilterUITests' do
    # Pods for testing
  end

end
